const NOMES_PROMOTORIAS = {
  1: 'Promotorias de Investigação (com JVDFM)',
  2: 'Promotorias de Investigação (Delegacias Distritais)',
  3: 'Promotorias de Tutela Coletiva (Meio Ambiente e Consumidor)',
  4: 'Promotorias Criminais, de Juizados e/ou Investigações',

  20: 'Tutela Coletiva Ampla',
  21: 'Tutela Coletiva Ampla sem Idoso ou com Idoso Residual',
  22: 'Tutela Coletiva Ampla sem Idoso e Saúde',
  23: 'Tutela Coletiva - Cidadania e Consumidor',
  24: 'Tutela Coletiva - Meio Ambiente e Consumidor',
  25: 'Tutela Coletiva - Cidadania Ampla',
  26: 'Tutela Coletiva - Cidadania Pura',
  27: 'Tutela Coletiva - Consumidor',
  28: 'Tutela Coletiva - Meio Ambiente',
  29: 'Tutela Coletiva - Ordem Urbanística',
  30: 'Tutela Coletiva - Educação',
  31: 'Tutela Coletiva - Infância e Juventude',
  32: 'Tutela Coletiva - Saúde',
  33: 'Tutela Coletiva - Sem Ranking',
  180: 'Tutela Coletiva - Sistema Prisional e Estabelecimentos de Aplicação de Medidas Socioeducativas',
  181: 'Tutela Coletiva - Proteção do Idoso e da Pessoa com Deficiência',
  182: ' Tutela Coletiva - Prestacionais',
  183: 'Tutela Coletiva - Meio Ambiente, Consumidor e Saúde',
  200: 'PIPs Territoriais 1a CI',
  201: 'PIPs Territoriais 2a CI',
  202: 'PIPs Territoriais 3a CI',
  203: 'PIPs Territoriais Interior',
  204: 'PIPs Violência Doméstica 1a CI',
  205: 'PIPs Violência Doméstica 2a CI',
  206: 'PIPs Violência Doméstica 3a CI',
  207: 'PIPs Especializadas 1a CI',
  208: 'PIPs Especializadas 2a CI',
  209: 'PIPs Especializadas 3a CI',
};

export default NOMES_PROMOTORIAS;
